Description: Configuration for Adapter participant for SIL Kit Adapter for Byte Stream Socket
ParticipantName: SilKitAdapterByteStreamSocket
Middleware:
  RegistryUri: silkit://localhost:8501
Logging:
  Sinks:
  - Type: Stdout
    Level: Debug
